### PR TITLE
Dockerized agent for moped test instance commissioning

### PR DESCRIPTION
**Pull request by chiaberry**
~⚠️ Please do not merge this until [PR 54](https://github.com/cityofaustin/atd-prefect/pull/54) has been merged, as it updates `moped-project`.~ ✅

### CODE REVIEW

**Comment by Charlie-Henry** [comment]
@chiaberry I noticed our `moped` folder in the `flows` directory should be capitalized `Moped` in order to be correctly auto-registered with the Project: `Moped`. I'll be opening a PR to delete the current `moped` directory in main

**Comment by frankhereford** [comment]
@Charlie-Henry wrote:
> @chiaberry I noticed our `moped` folder in the `flows` directory should be capitalized `Moped` in order to be correctly auto-registered with the Project: `Moped`. I'll be opening a PR to delete the current `moped` directory in main

I'd like to discuss this before this change is worked on. The moped flows folder contains a dockerized agent and is not currently compatible with the CI in place. I may be missing something, but I'd like to keep folders lower-cased since it's the usual custom.

**Comment by chiaberry** [comment]
> @Charlie-Henry wrote:
> 
> > @chiaberry I noticed our `moped` folder in the `flows` directory should be capitalized `Moped` in order to be correctly auto-registered with the Project: `Moped`. I'll be opening a PR to delete the current `moped` directory in main
> 
> I'd like to discuss this before this change is worked on. The moped flows folder contains a dockerized agent and is not currently compatible with the CI in place. I may be missing something, but I'd like to keep folders lower-cased since it's the usual custom.

our custom is to name the folder the same as the project name -- the project name is Moped (https://github.com/cityofaustin/atd-moped/blob/4e686b59f25cfd0db3dd370e69a29ca6acdf7b86/moped-etl/prefect/moped_test_create_flow.py#L381)

so we'd need to change one of them, either the folder or the project name

**Comment by chiaberry** [comment]
@frankhereford I'll do the once over and the requesting of reviews, I just havent gotten to it yet.

**Comment by frankhereford** [comment]
@chiaberry and I were able to sync briefly on the topic of folder names. A proposal that came out of our conversation is to take the `vision-zero` existing folder and the `moped` folder created in this PR and move them both into a seperate directory created for dockerized-agents. There is no working CI for them at this time.

Doing so would get the mixed bag of types of approaches out of the same folder, simplifying task of writing new dockerized-agent CI, maintaining the effectiveness of the CI in place for flows written in the more traditional environment and making sure that none of the existing stuff attempts to operate on dockerized agents, as it's not applicable.

**Review by frankhereford — APPROVED** [review]
I'm excited to see this headed toward `main`. ~The brevity of the diff makes me fear that some portion of this work has accidentally already been merged, likely by a mis-targeted PR, such as the one I put in yesterday.~ I think now that I was wrong. I was just reviewing [the sibling PR](https://github.com/cityofaustin/atd-prefect/pull/43) in advance of our prefect meeting today, and it's where the real lionshare of the work resides. This PR is more concerning the tooling around the dockerized-agent which runs the agent for moped deployments.

In lieu of testing, I think this is ready to merge simply by being in active use for quite a while. If you'd like a more detailed testing regime, please let me know, and I'll try to come up with something.

**Comment by chiaberry** [comment]
@frankhereford Yeah, the bulk of the changes are in the moped branch. If I recall correctly we agreed as a team that these approvals are just to approve merging to main since they have been in use for a while now, so thats been our "test"

I am a little fuzzy on what needs to be done on atd-data03 after this is merged, I put it on the agenda for the prefect meeting. I think it is just checkout the main branch and pull to get the updates, but I feel like I may be missing something.

**Comment by frankhereford** [comment]
@chiaberry wrote:

> I am a little fuzzy on what needs to be done on atd-data03 after this is merged, I put it on the agenda for the prefect meeting. I think it is just checkout the main branch and pull to get the updates, but I feel like I may be missing something.

You're right on the money. It's been my experience that this works pretty OK:

* Check that there are no flows running via the prefect cloud ui
* If so, stop the dockerized agent by going into its directory in the flows directory and `docker-compose stop`ing
* Do whatever `git` operations are required to get the code one wants running in place.
* `docker-compose build` if there have been changes to the dockerized agent environment, or really, building isn't a bad thing to do anyway. Sometimes it yields a head-scratcher like what Mike just handled with his `pgloader` related PR, but that head-scratcher is going to come at some point - be it now or when we are trying to roll out material changes to the environment such as adding new libraries or tooling.
* `docker-compose up -d` to start up the agent again
* `docker-compose exec -it <container name> bash` to attach to the agent
* Reregister each flow in its updated form with prefect

**Review by roseeichelmann — APPROVED** [review]

**Review by mddilley — APPROVED** [review]
Approving based on it being in use and enabling our current Moped test instances 🚀

**Pull request merged**
