### PR TITLE
Use requirements.txt in the Prefect dockerized-agent system

### PR DESCRIPTION
**Pull request by frankhereford**
This PR intends to close https://github.com/cityofaustin/atd-data-tech/issues/9801. I opened that issue yesterday under the misconception that this was going to be more work than it was. Thanks to @johnclary for his insight and help!

This change moves the definition of the python libraries available to VZ flows out of the Dockerfile and into a requirements.txt. This enables version pinning, which will be helpful with the shortly forthcoming Prefect 2.0 release. This change should have gone in with the PRs that I merged yesterday.

### CODE REVIEW

**Comment by johnclary** [comment]
@frankhereford this looks good, but i typically only add to `requirements.txt` the packages that i `pip install` for my project, and happily let the dependent packages' dependencies float to their maintainers' preference. you can also pin these to a minor version, if you're comfortable with that. [Example](https://github.com/cityofaustin/atd-knack-services/blob/production/requirements_production.txt).

**Review by johnclary — APPROVED** [review]
🚢

**Review by mddilley — APPROVED** [review]
🛥️ 👍

**Review by chiaberry — APPROVED** [review]

**Review by Charlie-Henry — APPROVED** [review]
✅

**Pull request merged**
